const bcrypt = require('bcryptjs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../../.env') });
const { sequelize, User, Lease, Escalation, Negotiation, Portfolio, MarketComp, LeaseAlert, AuditLog } = require('../models');

async function seed() {
  try {
    await sequelize.authenticate();
    await sequelize.sync({ force: true });
    console.log('Database synced (tables recreated)');

    // Users
    if (!process.env.DEMO_ADMIN_PASSWORD || process.env.DEMO_ADMIN_PASSWORD.length < 12) throw new Error('DEMO_ADMIN_PASSWORD (12+ characters) is required');
    const hashedPassword = await bcrypt.hash(process.env.DEMO_ADMIN_PASSWORD, 10);
    const users = await User.bulkCreate([
      { email: 'admin@leaseanalyzer.com', password: hashedPassword, name: 'Sarah Johnson', role: 'admin' },
      { email: 'analyst@leaseanalyzer.com', password: hashedPassword, name: 'Michael Chen', role: 'analyst' },
      { email: 'manager@leaseanalyzer.com', password: hashedPassword, name: 'Emily Davis', role: 'manager' }
    ], { returning: true });
    console.log('Users seeded');

    // 15 Leases
    await Lease.bulkCreate([
      { tenantName: 'Acme Corporation', propertyAddress: '100 Market St, San Francisco, CA 94105', propertyType: 'Office', leaseType: 'Full Service Gross', startDate: '2023-01-01', endDate: '2028-12-31', monthlyRent: 45000, annualRent: 540000, squareFootage: 12000, rentPerSqFt: 45.00, securityDeposit: 135000, leaseTermMonths: 72, escalationClause: '3% annual increase', renewalOption: 'Two 5-year options at market rate', specialProvisions: 'Right of first refusal on adjacent space', status: 'Active' },
      { tenantName: 'TechVenture Labs', propertyAddress: '200 Broadway, New York, NY 10007', propertyType: 'Office', leaseType: 'Modified Gross', startDate: '2022-06-01', endDate: '2027-05-31', monthlyRent: 62000, annualRent: 744000, squareFootage: 15000, rentPerSqFt: 49.60, securityDeposit: 186000, leaseTermMonths: 60, escalationClause: 'CPI-based with 5% cap', renewalOption: 'One 5-year option', specialProvisions: 'Subletting permitted with landlord consent', status: 'Active' },
      { tenantName: 'Global Pharma Inc', propertyAddress: '500 Research Dr, Cambridge, MA 02139', propertyType: 'Lab/Office', leaseType: 'Triple Net', startDate: '2021-03-01', endDate: '2031-02-28', monthlyRent: 125000, annualRent: 1500000, squareFootage: 30000, rentPerSqFt: 50.00, securityDeposit: 375000, leaseTermMonths: 120, escalationClause: '3.5% fixed annual escalation', renewalOption: 'Two 5-year options at 95% market', specialProvisions: 'Hazmat usage permitted, dedicated HVAC', status: 'Active' },
      { tenantName: 'Metro Retail Group', propertyAddress: '888 Michigan Ave, Chicago, IL 60611', propertyType: 'Retail', leaseType: 'Percentage Lease', startDate: '2023-09-01', endDate: '2033-08-31', monthlyRent: 35000, annualRent: 420000, squareFootage: 8000, rentPerSqFt: 52.50, securityDeposit: 105000, leaseTermMonths: 120, escalationClause: 'Greater of 3% or CPI', renewalOption: 'One 10-year option', specialProvisions: '6% percentage rent above $5M breakpoint', status: 'Active' },
      { tenantName: 'CloudScale Systems', propertyAddress: '1500 Tech Pkwy, Austin, TX 78701', propertyType: 'Office', leaseType: 'Full Service Gross', startDate: '2024-01-01', endDate: '2029-12-31', monthlyRent: 28000, annualRent: 336000, squareFootage: 9500, rentPerSqFt: 35.37, securityDeposit: 84000, leaseTermMonths: 72, escalationClause: '2.5% annual increase', renewalOption: 'Two 3-year options', specialProvisions: 'Early termination option at month 48 with 6-month penalty', status: 'Active' },
      { tenantName: 'Pacific Trading Co', propertyAddress: '2200 Harbor Blvd, Los Angeles, CA 90012', propertyType: 'Industrial', leaseType: 'Triple Net', startDate: '2022-01-01', endDate: '2032-12-31', monthlyRent: 55000, annualRent: 660000, squareFootage: 45000, rentPerSqFt: 14.67, securityDeposit: 165000, leaseTermMonths: 132, escalationClause: '3% annual with CPI floor', renewalOption: 'One 5-year option at market', specialProvisions: '24/7 access, truck court usage', status: 'Active' },
      { tenantName: 'FirstBank Financial', propertyAddress: '300 Financial Center, Charlotte, NC 28202', propertyType: 'Office', leaseType: 'Full Service Gross', startDate: '2020-07-01', endDate: '2030-06-30', monthlyRent: 95000, annualRent: 1140000, squareFootage: 25000, rentPerSqFt: 45.60, securityDeposit: 285000, leaseTermMonths: 120, escalationClause: '3% annual increase', renewalOption: 'Two 5-year options', specialProvisions: 'Building signage rights, reserved parking', status: 'Active' },
      { tenantName: 'Urban Fitness Co', propertyAddress: '450 5th Ave, Seattle, WA 98101', propertyType: 'Retail', leaseType: 'Modified Gross', startDate: '2023-04-01', endDate: '2033-03-31', monthlyRent: 22000, annualRent: 264000, squareFootage: 6000, rentPerSqFt: 44.00, securityDeposit: 66000, leaseTermMonths: 120, escalationClause: 'CPI annually, 4% cap', renewalOption: 'One 5-year option', specialProvisions: 'Extended hours permitted, signage rights', status: 'Active' },
      { tenantName: 'DataCore Analytics', propertyAddress: '700 Innovation Way, Denver, CO 80202', propertyType: 'Office', leaseType: 'Full Service Gross', startDate: '2024-03-01', endDate: '2029-02-28', monthlyRent: 18500, annualRent: 222000, squareFootage: 6500, rentPerSqFt: 34.15, securityDeposit: 55500, leaseTermMonths: 60, escalationClause: '3% annual', renewalOption: 'One 3-year option', specialProvisions: 'Contraction option at month 36', status: 'Active' },
      { tenantName: 'Gourmet Holdings LLC', propertyAddress: '55 Peachtree St, Atlanta, GA 30303', propertyType: 'Retail', leaseType: 'Percentage Lease', startDate: '2023-01-01', endDate: '2032-12-31', monthlyRent: 15000, annualRent: 180000, squareFootage: 4500, rentPerSqFt: 40.00, securityDeposit: 45000, leaseTermMonths: 120, escalationClause: '2.5% annual', renewalOption: 'Two 5-year options', specialProvisions: '5% percentage rent above $3M, patio usage rights', status: 'Active' },
      { tenantName: 'MedTech Solutions', propertyAddress: '1200 Medical Dr, Houston, TX 77030', propertyType: 'Medical Office', leaseType: 'Modified Gross', startDate: '2022-09-01', endDate: '2032-08-31', monthlyRent: 42000, annualRent: 504000, squareFootage: 11000, rentPerSqFt: 45.82, securityDeposit: 126000, leaseTermMonths: 120, escalationClause: '3% annual with CPI adjustment', renewalOption: 'One 10-year option', specialProvisions: 'Medical waste disposal, after-hours HVAC', status: 'Active' },
      { tenantName: 'Sterling Law Partners', propertyAddress: '1 Liberty Plaza, Miami, FL 33131', propertyType: 'Office', leaseType: 'Full Service Gross', startDate: '2021-01-01', endDate: '2030-12-31', monthlyRent: 75000, annualRent: 900000, squareFootage: 18000, rentPerSqFt: 50.00, securityDeposit: 225000, leaseTermMonths: 120, escalationClause: '3% annual fixed', renewalOption: 'Two 5-year options at 95% market', specialProvisions: 'Conference center access, 2 reserved parking per 1000 SF', status: 'Active' },
      { tenantName: 'EcoLogistics Inc', propertyAddress: '3500 Distribution Way, Phoenix, AZ 85034', propertyType: 'Industrial', leaseType: 'Triple Net', startDate: '2023-06-01', endDate: '2030-05-31', monthlyRent: 38000, annualRent: 456000, squareFootage: 50000, rentPerSqFt: 9.12, securityDeposit: 114000, leaseTermMonths: 84, escalationClause: '2.75% annual', renewalOption: 'Two 5-year options', specialProvisions: 'Cross-dock capability, 32ft clear height', status: 'Active' },
      { tenantName: 'Creative Media Agency', propertyAddress: '800 Sunset Blvd, Los Angeles, CA 90028', propertyType: 'Creative Office', leaseType: 'Modified Gross', startDate: '2024-02-01', endDate: '2029-01-31', monthlyRent: 32000, annualRent: 384000, squareFootage: 8500, rentPerSqFt: 45.18, securityDeposit: 96000, leaseTermMonths: 60, escalationClause: '3% annual', renewalOption: 'One 3-year option', specialProvisions: 'Rooftop access, studio buildout allowance', status: 'Active' },
      { tenantName: 'National Insurance Group', propertyAddress: '600 Congress Ave, Austin, TX 78701', propertyType: 'Office', leaseType: 'Full Service Gross', startDate: '2022-11-01', endDate: '2029-10-31', monthlyRent: 48000, annualRent: 576000, squareFootage: 14000, rentPerSqFt: 41.14, securityDeposit: 144000, leaseTermMonths: 84, escalationClause: '3% annual escalation', renewalOption: 'One 5-year option', specialProvisions: 'Expansion option for 5000 SF on same floor', status: 'Active' }
    ]);
    console.log('Leases seeded (15 items)');

    // 15 Escalations
    await Escalation.bulkCreate([
      { leaseId: 1, tenantName: 'Acme Corporation', propertyAddress: '100 Market St, San Francisco, CA', currentRent: 45000, escalationType: 'Fixed Percentage', escalationRate: 3.00, escalationSchedule: 'Annual', startDate: '2023-01-01', endDate: '2028-12-31', cpiIndex: 'CPI-U West', capRate: null, floorRate: null, notes: 'Standard 3% annual escalation', status: 'Active' },
      { leaseId: 2, tenantName: 'TechVenture Labs', propertyAddress: '200 Broadway, New York, NY', currentRent: 62000, escalationType: 'CPI-Based', escalationRate: 0, escalationSchedule: 'Annual', startDate: '2022-06-01', endDate: '2027-05-31', cpiIndex: 'CPI-U Northeast', capRate: 5.00, floorRate: 2.00, notes: 'CPI with 5% cap and 2% floor', status: 'Active' },
      { leaseId: 3, tenantName: 'Global Pharma Inc', propertyAddress: '500 Research Dr, Cambridge, MA', currentRent: 125000, escalationType: 'Fixed Percentage', escalationRate: 3.50, escalationSchedule: 'Annual', startDate: '2021-03-01', endDate: '2031-02-28', notes: 'Fixed 3.5% annual - premium lab space', status: 'Active' },
      { leaseId: 4, tenantName: 'Metro Retail Group', propertyAddress: '888 Michigan Ave, Chicago, IL', currentRent: 35000, escalationType: 'Greater of Fixed or CPI', escalationRate: 3.00, escalationSchedule: 'Annual', startDate: '2023-09-01', endDate: '2033-08-31', cpiIndex: 'CPI-U Midwest', notes: 'Greater of 3% or CPI', status: 'Active' },
      { leaseId: 5, tenantName: 'CloudScale Systems', propertyAddress: '1500 Tech Pkwy, Austin, TX', currentRent: 28000, escalationType: 'Fixed Percentage', escalationRate: 2.50, escalationSchedule: 'Annual', startDate: '2024-01-01', endDate: '2029-12-31', notes: 'Below market escalation rate', status: 'Active' },
      { leaseId: 6, tenantName: 'Pacific Trading Co', propertyAddress: '2200 Harbor Blvd, Los Angeles, CA', currentRent: 55000, escalationType: 'CPI with Floor', escalationRate: 0, escalationSchedule: 'Annual', startDate: '2022-01-01', endDate: '2032-12-31', cpiIndex: 'CPI-U West', floorRate: 3.00, notes: 'CPI-based with 3% floor', status: 'Active' },
      { leaseId: 7, tenantName: 'FirstBank Financial', propertyAddress: '300 Financial Center, Charlotte, NC', currentRent: 95000, escalationType: 'Fixed Percentage', escalationRate: 3.00, escalationSchedule: 'Annual', startDate: '2020-07-01', endDate: '2030-06-30', notes: 'Standard bank lease escalation', status: 'Active' },
      { leaseId: 8, tenantName: 'Urban Fitness Co', propertyAddress: '450 5th Ave, Seattle, WA', currentRent: 22000, escalationType: 'CPI-Based', escalationRate: 0, escalationSchedule: 'Annual', startDate: '2023-04-01', endDate: '2033-03-31', cpiIndex: 'CPI-U West', capRate: 4.00, notes: 'CPI with 4% cap', status: 'Active' },
      { leaseId: 9, tenantName: 'DataCore Analytics', propertyAddress: '700 Innovation Way, Denver, CO', currentRent: 18500, escalationType: 'Fixed Percentage', escalationRate: 3.00, escalationSchedule: 'Annual', startDate: '2024-03-01', endDate: '2029-02-28', notes: 'Standard escalation', status: 'Active' },
      { leaseId: 10, tenantName: 'Gourmet Holdings LLC', propertyAddress: '55 Peachtree St, Atlanta, GA', currentRent: 15000, escalationType: 'Fixed Percentage', escalationRate: 2.50, escalationSchedule: 'Annual', startDate: '2023-01-01', endDate: '2032-12-31', notes: 'Restaurant tenant - lower escalation', status: 'Active' },
      { leaseId: 11, tenantName: 'MedTech Solutions', propertyAddress: '1200 Medical Dr, Houston, TX', currentRent: 42000, escalationType: 'CPI with Adjustment', escalationRate: 3.00, escalationSchedule: 'Annual', startDate: '2022-09-01', endDate: '2032-08-31', cpiIndex: 'CPI-U South', notes: 'CPI adjustment with 3% minimum', status: 'Active' },
      { leaseId: 12, tenantName: 'Sterling Law Partners', propertyAddress: '1 Liberty Plaza, Miami, FL', currentRent: 75000, escalationType: 'Fixed Percentage', escalationRate: 3.00, escalationSchedule: 'Annual', startDate: '2021-01-01', endDate: '2030-12-31', notes: 'Premium law firm lease terms', status: 'Active' },
      { leaseId: 13, tenantName: 'EcoLogistics Inc', propertyAddress: '3500 Distribution Way, Phoenix, AZ', currentRent: 38000, escalationType: 'Fixed Percentage', escalationRate: 2.75, escalationSchedule: 'Annual', startDate: '2023-06-01', endDate: '2030-05-31', notes: 'Industrial standard escalation', status: 'Active' },
      { leaseId: 14, tenantName: 'Creative Media Agency', propertyAddress: '800 Sunset Blvd, Los Angeles, CA', currentRent: 32000, escalationType: 'Fixed Percentage', escalationRate: 3.00, escalationSchedule: 'Annual', startDate: '2024-02-01', endDate: '2029-01-31', notes: 'Creative space escalation', status: 'Active' },
      { leaseId: 15, tenantName: 'National Insurance Group', propertyAddress: '600 Congress Ave, Austin, TX', currentRent: 48000, escalationType: 'Fixed Percentage', escalationRate: 3.00, escalationSchedule: 'Annual', startDate: '2022-11-01', endDate: '2029-10-31', notes: 'Insurance company standard terms', status: 'Active' }
    ]);
    console.log('Escalations seeded (15 items)');

    // 15 Negotiations
    await Negotiation.bulkCreate([
      { leaseId: 1, tenantName: 'Acme Corporation', propertyAddress: '100 Market St, San Francisco, CA', currentTermEnd: '2028-12-31', renewalType: 'Renewal', proposedTermMonths: 60, currentRent: 45000, proposedRent: 52000, marketRent: 50000, tenantImprovementAllowance: 45000, freeRentMonths: 2, negotiationStatus: 'In Progress', landlordPriorities: 'Maximize rent, long term commitment', tenantPriorities: 'TI allowance, flexible term', notes: 'Tenant considering expansion' },
      { leaseId: 2, tenantName: 'TechVenture Labs', propertyAddress: '200 Broadway, New York, NY', currentTermEnd: '2027-05-31', renewalType: 'Renewal', proposedTermMonths: 60, currentRent: 62000, proposedRent: 68000, marketRent: 72000, tenantImprovementAllowance: 60000, freeRentMonths: 3, negotiationStatus: 'Pending', landlordPriorities: 'Market rate rent, credit quality', tenantPriorities: 'Below market rent, expansion option' },
      { leaseId: 3, tenantName: 'Global Pharma Inc', propertyAddress: '500 Research Dr, Cambridge, MA', currentTermEnd: '2031-02-28', renewalType: 'Early Renewal', proposedTermMonths: 120, currentRent: 125000, proposedRent: 140000, marketRent: 145000, tenantImprovementAllowance: 150000, freeRentMonths: 4, negotiationStatus: 'In Progress', landlordPriorities: 'Long term commitment, rent growth', tenantPriorities: 'Lab improvements, expansion rights' },
      { leaseId: 4, tenantName: 'Metro Retail Group', propertyAddress: '888 Michigan Ave, Chicago, IL', currentTermEnd: '2033-08-31', renewalType: 'Renewal', proposedTermMonths: 120, currentRent: 35000, proposedRent: 40000, marketRent: 42000, tenantImprovementAllowance: 25000, freeRentMonths: 2, negotiationStatus: 'Pending', landlordPriorities: 'Percentage rent increase, longer term', tenantPriorities: 'Lower breakpoint, TI allowance' },
      { leaseId: 5, tenantName: 'CloudScale Systems', propertyAddress: '1500 Tech Pkwy, Austin, TX', currentTermEnd: '2029-12-31', renewalType: 'Early Renewal', proposedTermMonths: 84, currentRent: 28000, proposedRent: 32000, marketRent: 34000, tenantImprovementAllowance: 30000, freeRentMonths: 2, negotiationStatus: 'In Progress', landlordPriorities: 'Remove early termination clause', tenantPriorities: 'Keep flexibility, moderate increase' },
      { leaseId: 6, tenantName: 'Pacific Trading Co', propertyAddress: '2200 Harbor Blvd, Los Angeles, CA', currentTermEnd: '2032-12-31', renewalType: 'Expansion', proposedTermMonths: 60, currentRent: 55000, proposedRent: 62000, marketRent: 60000, tenantImprovementAllowance: 40000, freeRentMonths: 1, negotiationStatus: 'Approved', landlordPriorities: 'Fill adjacent vacancy, above market rent', tenantPriorities: 'Contiguous space, dock doors' },
      { leaseId: 7, tenantName: 'FirstBank Financial', propertyAddress: '300 Financial Center, Charlotte, NC', currentTermEnd: '2030-06-30', renewalType: 'Renewal', proposedTermMonths: 120, currentRent: 95000, proposedRent: 105000, marketRent: 100000, tenantImprovementAllowance: 100000, freeRentMonths: 3, negotiationStatus: 'In Progress', landlordPriorities: 'Long term anchor tenant, market rent', tenantPriorities: 'Signage, parking, modernization' },
      { leaseId: 8, tenantName: 'Urban Fitness Co', propertyAddress: '450 5th Ave, Seattle, WA', currentTermEnd: '2033-03-31', renewalType: 'Modification', proposedTermMonths: 60, currentRent: 22000, proposedRent: 24000, marketRent: 26000, tenantImprovementAllowance: 15000, freeRentMonths: 1, negotiationStatus: 'Pending', landlordPriorities: 'Maintain occupancy, gradual increase', tenantPriorities: 'Renovate space, add outdoor area' },
      { leaseId: 9, tenantName: 'DataCore Analytics', propertyAddress: '700 Innovation Way, Denver, CO', currentTermEnd: '2029-02-28', renewalType: 'Renewal', proposedTermMonths: 60, currentRent: 18500, proposedRent: 21000, marketRent: 22000, tenantImprovementAllowance: 20000, freeRentMonths: 2, negotiationStatus: 'Pending', landlordPriorities: 'Remove contraction option, market rent', tenantPriorities: 'Moderate increase, parking' },
      { leaseId: 10, tenantName: 'Gourmet Holdings LLC', propertyAddress: '55 Peachtree St, Atlanta, GA', currentTermEnd: '2032-12-31', renewalType: 'Renewal', proposedTermMonths: 120, currentRent: 15000, proposedRent: 17500, marketRent: 18000, tenantImprovementAllowance: 12000, freeRentMonths: 1, negotiationStatus: 'In Progress', landlordPriorities: 'Higher percentage rent, base increase', tenantPriorities: 'Kitchen renovation, patio expansion' },
      { leaseId: 11, tenantName: 'MedTech Solutions', propertyAddress: '1200 Medical Dr, Houston, TX', currentTermEnd: '2032-08-31', renewalType: 'Early Renewal', proposedTermMonths: 120, currentRent: 42000, proposedRent: 48000, marketRent: 50000, tenantImprovementAllowance: 55000, freeRentMonths: 3, negotiationStatus: 'In Progress', landlordPriorities: 'Lock in long term, medical TI cost sharing', tenantPriorities: 'Equipment installation, exam room buildout' },
      { leaseId: 12, tenantName: 'Sterling Law Partners', propertyAddress: '1 Liberty Plaza, Miami, FL', currentTermEnd: '2030-12-31', renewalType: 'Renewal', proposedTermMonths: 120, currentRent: 75000, proposedRent: 82000, marketRent: 80000, tenantImprovementAllowance: 80000, freeRentMonths: 4, negotiationStatus: 'Pending', landlordPriorities: 'Premium rent, long term', tenantPriorities: 'Prestigious finish, conference facilities' },
      { leaseId: 13, tenantName: 'EcoLogistics Inc', propertyAddress: '3500 Distribution Way, Phoenix, AZ', currentTermEnd: '2030-05-31', renewalType: 'Expansion', proposedTermMonths: 84, currentRent: 38000, proposedRent: 42000, marketRent: 40000, tenantImprovementAllowance: 20000, freeRentMonths: 1, negotiationStatus: 'Approved', landlordPriorities: 'Higher rate, longer commitment', tenantPriorities: 'Additional loading docks, yard space' },
      { leaseId: 14, tenantName: 'Creative Media Agency', propertyAddress: '800 Sunset Blvd, Los Angeles, CA', currentTermEnd: '2029-01-31', renewalType: 'Renewal', proposedTermMonths: 60, currentRent: 32000, proposedRent: 36000, marketRent: 38000, tenantImprovementAllowance: 30000, freeRentMonths: 2, negotiationStatus: 'In Progress', landlordPriorities: 'Market rate, longer term preferred', tenantPriorities: 'Studio upgrades, rooftop event space' },
      { leaseId: 15, tenantName: 'National Insurance Group', propertyAddress: '600 Congress Ave, Austin, TX', currentTermEnd: '2029-10-31', renewalType: 'Renewal', proposedTermMonths: 84, currentRent: 48000, proposedRent: 54000, marketRent: 52000, tenantImprovementAllowance: 45000, freeRentMonths: 2, negotiationStatus: 'Pending', landlordPriorities: 'Expansion commitment, above market', tenantPriorities: 'Modern space, collaboration areas' }
    ]);
    console.log('Negotiations seeded (15 items)');

    // 15 Portfolio items
    await Portfolio.bulkCreate([
      { propertyName: 'Market Street Tower', propertyAddress: '100 Market St, San Francisco, CA 94105', propertyType: 'Class A Office', totalSquareFootage: 350000, occupancyRate: 92.5, totalUnits: 28, occupiedUnits: 26, annualNOI: 12500000, propertyValue: 178571429, capRate: 7.0, debtService: 8500000, dscr: 1.47, yearBuilt: 2005, lastRenovation: 2020, market: 'San Francisco CBD', riskScore: 3.5, status: 'Active' },
      { propertyName: 'Broadway Commerce Center', propertyAddress: '200 Broadway, New York, NY 10007', propertyType: 'Class A Office', totalSquareFootage: 500000, occupancyRate: 95.0, totalUnits: 42, occupiedUnits: 40, annualNOI: 22000000, propertyValue: 314285714, capRate: 7.0, debtService: 15000000, dscr: 1.47, yearBuilt: 1998, lastRenovation: 2019, market: 'Manhattan Downtown', riskScore: 2.5, status: 'Active' },
      { propertyName: 'Cambridge Research Park', propertyAddress: '500 Research Dr, Cambridge, MA 02139', propertyType: 'Lab/Office', totalSquareFootage: 200000, occupancyRate: 98.0, totalUnits: 12, occupiedUnits: 12, annualNOI: 15000000, propertyValue: 250000000, capRate: 6.0, debtService: 10000000, dscr: 1.50, yearBuilt: 2010, lastRenovation: 2022, market: 'Cambridge Life Science', riskScore: 2.0, status: 'Active' },
      { propertyName: 'Michigan Avenue Shops', propertyAddress: '888 Michigan Ave, Chicago, IL 60611', propertyType: 'Retail', totalSquareFootage: 120000, occupancyRate: 88.0, totalUnits: 18, occupiedUnits: 16, annualNOI: 5500000, propertyValue: 73333333, capRate: 7.5, debtService: 3800000, dscr: 1.45, yearBuilt: 1985, lastRenovation: 2018, market: 'Chicago Magnificent Mile', riskScore: 4.0, status: 'Active' },
      { propertyName: 'Tech Parkway Campus', propertyAddress: '1500 Tech Pkwy, Austin, TX 78701', propertyType: 'Class A Office', totalSquareFootage: 280000, occupancyRate: 94.0, totalUnits: 22, occupiedUnits: 21, annualNOI: 9800000, propertyValue: 140000000, capRate: 7.0, debtService: 6500000, dscr: 1.51, yearBuilt: 2015, lastRenovation: 2023, market: 'Austin CBD', riskScore: 2.8, status: 'Active' },
      { propertyName: 'Harbor Distribution Center', propertyAddress: '2200 Harbor Blvd, Los Angeles, CA 90012', propertyType: 'Industrial', totalSquareFootage: 450000, occupancyRate: 100.0, totalUnits: 8, occupiedUnits: 8, annualNOI: 8200000, propertyValue: 164000000, capRate: 5.0, debtService: 5500000, dscr: 1.49, yearBuilt: 2000, lastRenovation: 2021, market: 'LA South Bay Industrial', riskScore: 2.2, status: 'Active' },
      { propertyName: 'Financial Center Plaza', propertyAddress: '300 Financial Center, Charlotte, NC 28202', propertyType: 'Class A Office', totalSquareFootage: 400000, occupancyRate: 91.0, totalUnits: 35, occupiedUnits: 32, annualNOI: 14000000, propertyValue: 200000000, capRate: 7.0, debtService: 9500000, dscr: 1.47, yearBuilt: 2002, lastRenovation: 2020, market: 'Charlotte Uptown', riskScore: 3.0, status: 'Active' },
      { propertyName: 'Fifth Avenue Retail', propertyAddress: '450 5th Ave, Seattle, WA 98101', propertyType: 'Retail', totalSquareFootage: 85000, occupancyRate: 90.0, totalUnits: 15, occupiedUnits: 14, annualNOI: 3800000, propertyValue: 54285714, capRate: 7.0, debtService: 2500000, dscr: 1.52, yearBuilt: 1995, lastRenovation: 2022, market: 'Seattle Downtown', riskScore: 3.5, status: 'Active' },
      { propertyName: 'Innovation Way Tower', propertyAddress: '700 Innovation Way, Denver, CO 80202', propertyType: 'Class B Office', totalSquareFootage: 180000, occupancyRate: 87.0, totalUnits: 20, occupiedUnits: 17, annualNOI: 5200000, propertyValue: 65000000, capRate: 8.0, debtService: 3500000, dscr: 1.49, yearBuilt: 1990, lastRenovation: 2019, market: 'Denver LoDo', riskScore: 4.5, status: 'Active' },
      { propertyName: 'Peachtree Retail Center', propertyAddress: '55 Peachtree St, Atlanta, GA 30303', propertyType: 'Retail', totalSquareFootage: 95000, occupancyRate: 85.0, totalUnits: 20, occupiedUnits: 17, annualNOI: 3200000, propertyValue: 42666667, capRate: 7.5, debtService: 2200000, dscr: 1.45, yearBuilt: 1988, lastRenovation: 2021, market: 'Atlanta Midtown', riskScore: 5.0, status: 'Active' },
      { propertyName: 'Medical Center Tower', propertyAddress: '1200 Medical Dr, Houston, TX 77030', propertyType: 'Medical Office', totalSquareFootage: 220000, occupancyRate: 96.0, totalUnits: 25, occupiedUnits: 24, annualNOI: 11000000, propertyValue: 157142857, capRate: 7.0, debtService: 7500000, dscr: 1.47, yearBuilt: 2008, lastRenovation: 2023, market: 'Houston Medical Center', riskScore: 2.5, status: 'Active' },
      { propertyName: 'Liberty Plaza Tower', propertyAddress: '1 Liberty Plaza, Miami, FL 33131', propertyType: 'Class A Office', totalSquareFootage: 320000, occupancyRate: 93.0, totalUnits: 30, occupiedUnits: 28, annualNOI: 13500000, propertyValue: 192857143, capRate: 7.0, debtService: 9000000, dscr: 1.50, yearBuilt: 2012, lastRenovation: 2022, market: 'Miami Brickell', riskScore: 3.0, status: 'Active' },
      { propertyName: 'Phoenix Distribution Hub', propertyAddress: '3500 Distribution Way, Phoenix, AZ 85034', propertyType: 'Industrial', totalSquareFootage: 380000, occupancyRate: 100.0, totalUnits: 6, occupiedUnits: 6, annualNOI: 6800000, propertyValue: 113333333, capRate: 6.0, debtService: 4500000, dscr: 1.51, yearBuilt: 2018, lastRenovation: null, market: 'Phoenix Sky Harbor', riskScore: 2.0, status: 'Active' },
      { propertyName: 'Sunset Creative Campus', propertyAddress: '800 Sunset Blvd, Los Angeles, CA 90028', propertyType: 'Creative Office', totalSquareFootage: 150000, occupancyRate: 96.0, totalUnits: 18, occupiedUnits: 17, annualNOI: 7200000, propertyValue: 120000000, capRate: 6.0, debtService: 4800000, dscr: 1.50, yearBuilt: 2016, lastRenovation: 2023, market: 'Hollywood/West LA', riskScore: 2.8, status: 'Active' },
      { propertyName: 'Congress Avenue Center', propertyAddress: '600 Congress Ave, Austin, TX 78701', propertyType: 'Class A Office', totalSquareFootage: 260000, occupancyRate: 93.0, totalUnits: 24, occupiedUnits: 22, annualNOI: 9200000, propertyValue: 131428571, capRate: 7.0, debtService: 6200000, dscr: 1.48, yearBuilt: 2013, lastRenovation: 2022, market: 'Austin CBD', riskScore: 2.8, status: 'Active' }
    ]);
    console.log('Portfolio items seeded (15 items)');

    // 15 Market Comps
    await MarketComp.bulkCreate([
      { propertyAddress: '150 California St, San Francisco, CA 94111', propertyType: 'Office', submarket: 'Financial District', market: 'San Francisco', squareFootage: 15000, askingRentPerSqFt: 72.00, effectiveRentPerSqFt: 65.00, occupancyRate: 93.0, leaseType: 'Full Service', tenantName: 'Fintech Solutions Inc', transactionDate: '2024-01-15', freeRentMonths: 3, tiAllowance: 65.00, escalationRate: 3.00, buildingClass: 'A', yearBuilt: 2008, parkingRatio: '1:1000', source: 'CoStar', notes: 'Strong tech demand in FiDi' },
      { propertyAddress: '345 Park Ave, New York, NY 10022', propertyType: 'Office', submarket: 'Midtown East', market: 'New York', squareFootage: 22000, askingRentPerSqFt: 85.00, effectiveRentPerSqFt: 78.00, occupancyRate: 96.0, leaseType: 'Full Service', tenantName: 'Global Advisory Group', transactionDate: '2024-02-20', freeRentMonths: 4, tiAllowance: 80.00, escalationRate: 3.00, buildingClass: 'A', yearBuilt: 2001, parkingRatio: 'N/A', source: 'CBRE', notes: 'Premium Midtown location' },
      { propertyAddress: '75 Binney St, Cambridge, MA 02142', propertyType: 'Lab/Office', submarket: 'Kendall Square', market: 'Cambridge', squareFootage: 35000, askingRentPerSqFt: 95.00, effectiveRentPerSqFt: 88.00, occupancyRate: 99.0, leaseType: 'Triple Net', tenantName: 'BioVenture Therapeutics', transactionDate: '2024-03-10', freeRentMonths: 2, tiAllowance: 120.00, escalationRate: 3.50, buildingClass: 'A', yearBuilt: 2015, parkingRatio: '2:1000', source: 'JLL', notes: 'Lab shortage driving premium rents' },
      { propertyAddress: '233 S Wacker Dr, Chicago, IL 60606', propertyType: 'Office', submarket: 'West Loop', market: 'Chicago', squareFootage: 18000, askingRentPerSqFt: 42.00, effectiveRentPerSqFt: 38.00, occupancyRate: 89.0, leaseType: 'Full Service', tenantName: 'Midwest Capital Partners', transactionDate: '2024-01-30', freeRentMonths: 3, tiAllowance: 55.00, escalationRate: 2.75, buildingClass: 'A', yearBuilt: 2009, parkingRatio: '1:1000', source: 'Cushman & Wakefield', notes: 'Strong Class A demand in West Loop' },
      { propertyAddress: '816 Congress Ave, Austin, TX 78701', propertyType: 'Office', submarket: 'CBD', market: 'Austin', squareFootage: 12000, askingRentPerSqFt: 52.00, effectiveRentPerSqFt: 47.00, occupancyRate: 91.0, leaseType: 'Full Service', tenantName: 'Digital Commerce Labs', transactionDate: '2024-04-05', freeRentMonths: 2, tiAllowance: 50.00, escalationRate: 3.00, buildingClass: 'A', yearBuilt: 2017, parkingRatio: '3:1000', source: 'CoStar', notes: 'Tech hub premium, new construction pipeline concern' },
      { propertyAddress: '1925 Century Park E, Los Angeles, CA 90067', propertyType: 'Office', submarket: 'Century City', market: 'Los Angeles', squareFootage: 20000, askingRentPerSqFt: 62.00, effectiveRentPerSqFt: 56.00, occupancyRate: 90.0, leaseType: 'Full Service', tenantName: 'Entertainment Law Group', transactionDate: '2024-02-15', freeRentMonths: 3, tiAllowance: 70.00, escalationRate: 3.00, buildingClass: 'A', yearBuilt: 2003, parkingRatio: '4:1000', source: 'CBRE', notes: 'Entertainment industry hub' },
      { propertyAddress: '227 W Trade St, Charlotte, NC 28202', propertyType: 'Office', submarket: 'Uptown', market: 'Charlotte', squareFootage: 25000, askingRentPerSqFt: 38.00, effectiveRentPerSqFt: 34.00, occupancyRate: 88.0, leaseType: 'Full Service', tenantName: 'Southeast Financial Corp', transactionDate: '2024-03-25', freeRentMonths: 3, tiAllowance: 45.00, escalationRate: 2.75, buildingClass: 'A', yearBuilt: 2006, parkingRatio: '2:1000', source: 'JLL', notes: 'Banking sector anchors demand' },
      { propertyAddress: '520 Pike St, Seattle, WA 98101', propertyType: 'Retail', submarket: 'Downtown Core', market: 'Seattle', squareFootage: 5000, askingRentPerSqFt: 55.00, effectiveRentPerSqFt: 48.00, occupancyRate: 87.0, leaseType: 'Modified Gross', tenantName: 'Pacific Northwest Outfitters', transactionDate: '2024-01-10', freeRentMonths: 2, tiAllowance: 40.00, escalationRate: 3.00, buildingClass: 'A', yearBuilt: 1998, parkingRatio: 'N/A', source: 'Marcus & Millichap', notes: 'Retail recovering post-pandemic' },
      { propertyAddress: '1700 Lincoln St, Denver, CO 80203', propertyType: 'Office', submarket: 'CBD', market: 'Denver', squareFootage: 14000, askingRentPerSqFt: 38.00, effectiveRentPerSqFt: 33.00, occupancyRate: 84.0, leaseType: 'Full Service', tenantName: 'Rocky Mountain Tech Inc', transactionDate: '2024-02-28', freeRentMonths: 4, tiAllowance: 50.00, escalationRate: 2.50, buildingClass: 'B+', yearBuilt: 1995, parkingRatio: '2:1000', source: 'Newmark', notes: 'Elevated concessions in Denver CBD' },
      { propertyAddress: '191 Peachtree St NE, Atlanta, GA 30303', propertyType: 'Office', submarket: 'Midtown', market: 'Atlanta', squareFootage: 16000, askingRentPerSqFt: 35.00, effectiveRentPerSqFt: 31.00, occupancyRate: 86.0, leaseType: 'Full Service', tenantName: 'Southern Data Services', transactionDate: '2024-03-15', freeRentMonths: 3, tiAllowance: 45.00, escalationRate: 2.75, buildingClass: 'A', yearBuilt: 2000, parkingRatio: '3:1000', source: 'Colliers', notes: 'Growing tech presence in Midtown' },
      { propertyAddress: '1100 Louisiana St, Houston, TX 77002', propertyType: 'Office', submarket: 'CBD', market: 'Houston', squareFootage: 20000, askingRentPerSqFt: 40.00, effectiveRentPerSqFt: 35.00, occupancyRate: 82.0, leaseType: 'Full Service', tenantName: 'Energy Capital Advisors', transactionDate: '2024-04-10', freeRentMonths: 5, tiAllowance: 60.00, escalationRate: 2.50, buildingClass: 'A', yearBuilt: 2007, parkingRatio: '2:1000', source: 'CoStar', notes: 'Energy sector recovery, high concessions' },
      { propertyAddress: '801 Brickell Ave, Miami, FL 33131', propertyType: 'Office', submarket: 'Brickell', market: 'Miami', squareFootage: 18000, askingRentPerSqFt: 58.00, effectiveRentPerSqFt: 53.00, occupancyRate: 94.0, leaseType: 'Full Service', tenantName: 'LatAm Investment Group', transactionDate: '2024-02-05', freeRentMonths: 2, tiAllowance: 55.00, escalationRate: 3.00, buildingClass: 'A', yearBuilt: 2014, parkingRatio: '3:1000', source: 'CBRE', notes: 'Strong migration-driven demand' },
      { propertyAddress: '4800 N Scottsdale Rd, Phoenix, AZ 85251', propertyType: 'Industrial', submarket: 'Sky Harbor', market: 'Phoenix', squareFootage: 55000, askingRentPerSqFt: 12.50, effectiveRentPerSqFt: 11.00, occupancyRate: 97.0, leaseType: 'Triple Net', tenantName: 'Southwest Logistics Corp', transactionDate: '2024-03-20', freeRentMonths: 1, tiAllowance: 10.00, escalationRate: 3.00, buildingClass: 'A', yearBuilt: 2020, parkingRatio: 'N/A', source: 'Prologis Research', notes: 'Industrial rents at all-time high' },
      { propertyAddress: '5900 Wilshire Blvd, Los Angeles, CA 90036', propertyType: 'Creative Office', submarket: 'Miracle Mile', market: 'Los Angeles', squareFootage: 10000, askingRentPerSqFt: 54.00, effectiveRentPerSqFt: 48.00, occupancyRate: 92.0, leaseType: 'Modified Gross', tenantName: 'West Coast Studios', transactionDate: '2024-01-25', freeRentMonths: 2, tiAllowance: 55.00, escalationRate: 3.00, buildingClass: 'B+', yearBuilt: 2012, parkingRatio: '3:1000', source: 'JLL', notes: 'Creative office demand resilient' },
      { propertyAddress: '401 Congress Ave, Austin, TX 78701', propertyType: 'Office', submarket: 'CBD', market: 'Austin', squareFootage: 30000, askingRentPerSqFt: 56.00, effectiveRentPerSqFt: 50.00, occupancyRate: 93.0, leaseType: 'Full Service', tenantName: 'Lone Star Capital Management', transactionDate: '2024-04-15', freeRentMonths: 3, tiAllowance: 60.00, escalationRate: 3.00, buildingClass: 'A+', yearBuilt: 2022, parkingRatio: '3:1000', source: 'CoStar', notes: 'Trophy asset, top-of-market rents' }
    ]);
    console.log('Market Comps seeded (15 items)');

    const addDays = (days) => {
      const date = new Date();
      date.setDate(date.getDate() + days);
      return date.toISOString().split('T')[0];
    };

    const alertTemplates = [
      { leaseId: 1, alertType: 'expiration', alertDate: addDays(15), message: 'Prepare Acme renewal packet and market comparison report.' },
      { leaseId: 2, alertType: 'expiration', alertDate: addDays(30), message: 'Review TechVenture Labs expiration and renewal strategy.' },
      { leaseId: 3, alertType: 'rent_review', alertDate: addDays(35), message: 'Review Global Pharma rent economics against life-science market comps.' },
      { leaseId: 4, alertType: 'market_threshold', alertDate: addDays(40), message: 'Check retail percentage rent breakpoint against updated market sales assumptions.' },
      { leaseId: 5, alertType: 'option_deadline', alertDate: addDays(45), message: 'CloudScale Systems early termination option review window.' },
      { leaseId: 6, alertType: 'option_exercise', alertDate: addDays(50), message: 'Confirm Pacific Trading renewal option notice requirements.' },
      { leaseId: 7, alertType: 'tenant_credit', alertDate: addDays(55), message: 'Update FirstBank credit review before renewal negotiation.' },
      { leaseId: 8, alertType: 'comparable_change', alertDate: addDays(58), message: 'Refresh fitness retail comparable rents before alert window closes.' },
      { leaseId: 9, alertType: 'rent_bump', alertDate: addDays(60), message: 'DataCore Analytics annual escalation notice and rent schedule update.' },
      { leaseId: 10, alertType: 'escalation', alertDate: addDays(70), message: 'Calculate Gourmet Holdings percentage rent and escalation exposure.' },
      { leaseId: 11, alertType: 'renewal', alertDate: addDays(75), message: 'Start MedTech Solutions renewal package and TI analysis.' },
      { leaseId: 12, alertType: 'rent_review', alertDate: addDays(80), message: 'Benchmark Sterling Law rent against premium office comps.' },
      { leaseId: 13, alertType: 'market_threshold', alertDate: addDays(85), message: 'Check Phoenix industrial rent threshold and logistics demand.' },
      { leaseId: 14, alertType: 'custom', alertDate: addDays(90), message: 'Confirm rooftop/studio access provisions before renewal planning.' },
      { leaseId: 15, alertType: 'option_deadline', alertDate: addDays(120), message: 'Track National Insurance expansion option and notice deadline.' }
    ];

    await LeaseAlert.bulkCreate(
      users.flatMap((user) => alertTemplates.map((alert) => ({ ...alert, userId: user.id })))
    );
    console.log('Lease alerts seeded (15 items per user)');

    await AuditLog.bulkCreate([
      { userId: users[0].id, action: 'create', entityType: 'lease', entityId: '1', title: 'Created lease for Acme Corporation', source: 'seed', details: { module: 'leases' } },
      { userId: users[0].id, action: 'create', entityType: 'lease', entityId: '2', title: 'Created lease for TechVenture Labs', source: 'seed', details: { module: 'leases' } },
      { userId: users[1].id, action: 'create', entityType: 'escalation', entityId: '1', title: 'Created escalation for Acme Corporation', source: 'seed', details: { module: 'escalations' } },
      { userId: users[1].id, action: 'update', entityType: 'escalation', entityId: '5', title: 'Updated escalation review for CloudScale Systems', source: 'seed', details: { fields: ['notes', 'status'] } },
      { userId: users[2].id, action: 'create', entityType: 'negotiation', entityId: '1', title: 'Created renewal negotiation for Acme Corporation', source: 'seed', details: { module: 'negotiations' } },
      { userId: users[2].id, action: 'update', entityType: 'negotiation', entityId: '6', title: 'Approved Pacific Trading expansion negotiation', source: 'seed', details: { status: 'Approved' } },
      { userId: users[0].id, action: 'create', entityType: 'portfolio', entityId: '1', title: 'Created portfolio property Market Street Tower', source: 'seed', details: { module: 'portfolio' } },
      { userId: users[1].id, action: 'create', entityType: 'marketComp', entityId: '1', title: 'Created market comp for 150 California St', source: 'seed', details: { market: 'San Francisco' } },
      { userId: users[0].id, action: 'create', entityType: 'alert', entityId: '1', title: 'Created expiration alert for Acme Corporation', source: 'seed', details: { module: 'alerts' } },
      { userId: users[2].id, action: 'run_ai', entityType: 'aiLab', entityId: 'lease-audit', title: 'Ran lease audit workflow', source: 'seed', details: { workflow: 'Lease Audit' } },
      { userId: users[1].id, action: 'run_ai', entityType: 'aiLab', entityId: 'comparison', title: 'Ran lease comparison workflow', source: 'seed', details: { workflow: 'Lease Comparison' } },
      { userId: users[0].id, action: 'export', entityType: 'report', entityId: 'leases-csv', title: 'Exported leases CSV', source: 'seed', details: { format: 'csv' } },
      { userId: users[2].id, action: 'create', entityType: 'notification', entityId: 'default', title: 'Created default notification set', source: 'seed', details: { count: 15 } },
      { userId: users[1].id, action: 'create', entityType: 'customView', entityId: 'clause-rules', title: 'Created clause rule workspace', source: 'seed', details: { module: 'customViews' } },
      { userId: users[0].id, action: 'run_ai', entityType: 'chatbot', entityId: 'assistant', title: 'Chatbot assistant enabled', source: 'seed', details: { placement: 'floating' } }
    ]);
    console.log('Audit logs seeded (15 items)');

    console.log('\n✅ Database seeding completed successfully!');
    console.log('Login credentials:');
    console.log('  Email: admin@leaseanalyzer.com');
    console.log('Demo login users provisioned from the local environment.');
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
}

seed();
